In [1]:
import pip


%pip install kagglehub[pandas-datasets]
%pip install openpyxl #Instalando dependência para abrir .XLSX

Collecting kagglehub[pandas-datasets]
  Downloading kagglehub-1.0.1-py3-none-any.whl (70 kB)
     ---------------------------------------- 0.0/70.6 kB ? eta -:--:--
     ---------------------------------------- 70.6/70.6 kB 4.0 MB/s eta 0:00:00
Collecting requests
  Downloading requests-2.33.1-py3-none-any.whl (64 kB)
     ---------------------------------------- 0.0/64.9 kB ? eta -:--:--
     ---------------------------------------- 64.9/64.9 kB ? eta 0:00:00
Collecting tqdm
  Downloading tqdm-4.67.3-py3-none-any.whl (78 kB)
     ---------------------------------------- 0.0/78.4 kB ? eta -:--:--
     ---------------------------------------- 78.4/78.4 kB ? eta 0:00:00
Collecting kagglesdk<1.0,>=0.1.22
  Downloading kagglesdk-0.1.23-py3-none-any.whl (217 kB)
     ---------------------------------------- 0.0/217.8 kB ? eta -:--:--
     ---------------------------------------- 217.8/217.8 kB ? eta 0:00:00
Collecting pyyaml
  Downloading pyyaml-6.0.3-cp310-cp310-win_amd64.whl (158 kB)
     ---------------------------------------- 0.0/158.6 kB ? eta -:--:--
     ---------------------------------------- 158.6/158.6 kB ? eta 0:00:00
Requirement already satisfied: packaging in c:\users\support\appdata\roaming\python\python310\site-packages (from kagglehub[pandas-datasets]) (26.2)
Collecting pandas
  Downloading pandas-2.3.3-cp310-cp310-win_amd64.whl (11.3 MB)
     ---------------------------------------- 0.0/11.3 MB ? eta -:--:--
     --------------- ----------------------- 4.5/11.3 MB 145.0 MB/s eta 0:00:01
     ---------------------------------- --- 10.4/11.3 MB 110.0 MB/s eta 0:00:01
     --------------------------------------- 11.3/11.3 MB 81.8 MB/s eta 0:00:00
Collecting protobuf
  Downloading protobuf-7.34.1-cp310-abi3-win_amd64.whl (437 kB)
     ---------------------------------------- 0.0/437.9 kB ? eta -:--:--
     ---------------------------------------- 437.9/437.9 kB ? eta 0:00:00
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\support\appdata\roaming\python\python310\site-packages (from pandas->kagglehub[pandas-datasets]) (2.9.0.post0)
Collecting pytz>=2020.1
  Downloading pytz-2026.2-py2.py3-none-any.whl (510 kB)
     ---------------------------------------- 0.0/510.1 kB ? eta -:--:--
     ---------------------------------------- 510.1/510.1 kB ? eta 0:00:00
Collecting tzdata>=2022.7
  Downloading tzdata-2026.2-py2.py3-none-any.whl (349 kB)
     ---------------------------------------- 0.0/349.3 kB ? eta -:--:--
     ---------------------------------------- 349.3/349.3 kB ? eta 0:00:00
Collecting numpy>=1.22.4
  Downloading numpy-2.2.6-cp310-cp310-win_amd64.whl (12.9 MB)
     ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
     ---------------- ---------------------- 5.5/12.9 MB 116.1 MB/s eta 0:00:01
     ------------------------------ ------- 10.5/12.9 MB 108.8 MB/s eta 0:00:01
     --------------------------------------  12.9/12.9 MB 93.0 MB/s eta 0:00:01
     --------------------------------------  12.9/12.9 MB 93.0 MB/s eta 0:00:01
     --------------------------------------- 12.9/12.9 MB 46.7 MB/s eta 0:00:00
Collecting urllib3<3,>=1.26
  Downloading urllib3-2.7.0-py3-none-any.whl (131 kB)
     ---------------------------------------- 0.0/131.1 kB ? eta -:--:--
     ---------------------------------------- 131.1/131.1 kB ? eta 0:00:00
Collecting idna<4,>=2.5
  Downloading idna-3.13-py3-none-any.whl (68 kB)
     ---------------------------------------- 0.0/68.6 kB ? eta -:--:--
     ---------------------------------------- 68.6/68.6 kB ? eta 0:00:00
Collecting certifi>=2023.5.7
  Downloading certifi-2026.4.22-py3-none-any.whl (135 kB)
     ---------------------------------------- 0.0/135.7 kB ? eta -:--:--
     ---------------------------------------- 135.7/135.7 kB ? eta 0:00:00
Collecting charset_normalizer<4,>=2
  Downloading charset_normalizer-3.4.7-cp310-cp310-win_amd64.whl (159 kB)
     ---------------------------------------- 0.0/159.2 kB ? eta -:--:--
     ---------------------------------------- 159.2/159.2 kB ? eta 0:00:00
Requirement already satisfied: colorama in c:\users\support\appdata\roaming\python\python310\site-packages (from tqdm->kagglehub[pandas-datasets]) (0.4.6)
Requirement already satisfied: six>=1.5 in c:\users\support\appdata\roaming\python\python310\site-packages (from python-dateutil>=2.8.2->pandas->kagglehub[pandas-datasets]) (1.17.0)
Installing collected packages: pytz, urllib3, tzdata, tqdm, pyyaml, protobuf, numpy, idna, charset_normalizer, certifi, requests, pandas, kagglesdk, kagglehub
Successfully installed certifi-2026.4.22 charset_normalizer-3.4.7 idna-3.13 kagglehub-1.0.1 kagglesdk-0.1.23 numpy-2.2.6 pandas-2.3.3 protobuf-7.34.1 pytz-2026.2 pyyaml-6.0.3 requests-2.33.1 tqdm-4.67.3 tzdata-2026.2 urllib3-2.7.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Note: you may need to restart the kernel to use updated packages.

ERROR: Invalid requirement: '#Instalando'

[notice] A new release of pip is available: 23.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [8]:
%pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
     ---------------------------------------- 0.0/250.9 kB ? eta -:--:--
     ------------------------------------- 250.9/250.9 kB 15.0 MB/s eta 0:00:00
Collecting et-xmlfile
  Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
%pip install matplotlib

Collecting matplotlib
  Downloading matplotlib-3.10.9-cp310-cp310-win_amd64.whl (8.2 MB)
     ---------------------------------------- 0.0/8.2 MB ? eta -:--:--
     -- ------------------------------------- 0.5/8.2 MB 10.9 MB/s eta 0:00:01
     ------ --------------------------------- 1.3/8.2 MB 16.4 MB/s eta 0:00:01
     ------------ --------------------------- 2.6/8.2 MB 20.4 MB/s eta 0:00:01
     ------------------- -------------------- 4.1/8.2 MB 23.5 MB/s eta 0:00:01
     -------------------------------- ------- 6.6/8.2 MB 30.2 MB/s eta 0:00:01
     ---------------------------------------- 8.2/8.2 MB 32.8 MB/s eta 0:00:00
Collecting cycler>=0.10
  Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Collecting fonttools>=4.22.0
  Downloading fonttools-4.62.1-cp310-cp310-win_amd64.whl (1.6 MB)
     ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
     ---------------------------------------- 1.6/1.6 MB 96.7 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.7 in c:\users\support\appdata\roaming\python\python310\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: packaging>=20.0 in c:\users\support\appdata\roaming\python\python310\site-packages (from matplotlib) (26.2)
Collecting pyparsing>=3
  Downloading pyparsing-3.3.2-py3-none-any.whl (122 kB)
     ---------------------------------------- 0.0/122.8 kB ? eta -:--:--
     -------------------------------------- 122.8/122.8 kB 7.0 MB/s eta 0:00:00
Collecting contourpy>=1.0.1
  Downloading contourpy-1.3.2-cp310-cp310-win_amd64.whl (221 kB)
     ---------------------------------------- 0.0/221.2 kB ? eta -:--:--
     ---------------------------------------- 221.2/221.2 kB ? eta 0:00:00
Requirement already satisfied: numpy>=1.23 in c:\users\support\appdata\local\programs\python\python310\lib\site-packages (from matplotlib) (2.2.6)
Collecting kiwisolver>=1.3.1
  Downloading kiwisolver-1.5.0-cp310-cp310-win_amd64.whl (73 kB)
     ---------------------------------------- 0.0/73.4 kB ? eta -:--:--
     ---------------------------------------- 73.4/73.4 kB ? eta 0:00:00
Collecting pillow>=8
  Downloading pillow-12.2.0-cp310-cp310-win_amd64.whl (7.1 MB)
     ---------------------------------------- 0.0/7.1 MB ? eta -:--:--
     ------------------------ --------------- 4.3/7.1 MB 133.1 MB/s eta 0:00:01
     ---------------------------------------  7.1/7.1 MB 90.6 MB/s eta 0:00:01
     ---------------------------------------- 7.1/7.1 MB 64.3 MB/s eta 0:00:00
Requirement already satisfied: six>=1.5 in c:\users\support\appdata\roaming\python\python310\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Installing collected packages: pyparsing, pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib
Successfully installed contourpy-1.3.2 cycler-0.12.1 fonttools-4.62.1 kiwisolver-1.5.0 matplotlib-3.10.9 pillow-12.2.0 pyparsing-3.3.2
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [9]:
import pandas as pd
import kagglehub
from kagglehub import KaggleDatasetAdapter
import matplotlib as plt
import openpyxl as opn

In [10]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = 'iFood.xlsx'

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "fayez7/ifood-marketing-campaigns",
  file_path,
  # Provide any additional arguments like 
  # sql_query or pandas_kwargs. See the 
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

print("First 5 records:", df.head())

C:\Users\Support\AppData\Local\Temp\ipykernel_30944\932273858.py:10: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

First 5 records:    Index  Income  Kidhome  Teenhome  Recency  MntWines  MntFruits  \
0   1001   58138        0         0       58       635         88
1   1002   46344        1         1       38        11          1
2   1003   71613        0         0       26       426         49
3   1004   26646        1         0       26        11          4
4   1005   58293        1         0       94       173         43

   MntMeatProducts  MntFishProducts  MntSweetProducts  ...  AcceptedCmp2  \
0              546              172                88  ...             0
1                6                2                 1  ...             0
2              127              111                21  ...             0
3               20               10                 3  ...             0
4              118               46                27  ...             0

   AcceptedCmp3  AcceptedCmp4  AcceptedCmp5  AcceptedCmpOverall  Complain  \
0             0             0             0                   0         0
1             0             0             0                   0         0
2             0             0             0                   0         0
3             0             0             0                   0         0
4             0             0             0                   0         0

   Age  Customer_Days  marital_status   education
0   63           2822          Single  Graduation
1   66           2272          Single  Graduation
2   55           2471        Together  Graduation
3   36           2298        Together  Graduation
4   39           2320         Married         PHD

[5 rows x 29 columns]

In [11]:
pd.DataFrame(df, columns=['Income','Age' , 'Customer_Days' , 'MntTotal']).sort_values(by='MntTotal', ascending=False)
#Quanto maior a Renda (Income) maior o gasto total(MntTotal)?

      Income  Age  Customer_Days  MntTotal
1467   87679   32           2496      2491
1159   90638   29           2295      2429
1547   90638   29           2295      2429
967    75759   51           2406      2304
1433   93790   50           2296      2304
...      ...  ...            ...       ...
149    30523   62           2522         8
1225    1730   49           2201         7
2097   33590   46           2397         6
961     4861   55           2166         5
1499    3502   47           2601         4

[2205 rows x 4 columns]

In [12]:
df.tail()

,Index,Income,Kidhome,Teenhome,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,...,AcceptedCmp2,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmpOverall,Complain,Age,Customer_Days,marital_status,education
2200,3201,61223,0,1,46,709,43,182,42,118,...,0,0,0,0,0,0,53,2540,Married,Graduation
2201,3202,64014,2,1,56,406,0,30,0,0,...,0,0,0,0,1,0,74,2178,Together,PHD
2202,3203,56981,0,0,91,908,48,217,32,12,...,0,0,1,0,1,0,39,2314,Divorced,Graduation
2203,3204,69245,0,1,8,428,30,214,80,30,...,0,0,0,0,0,0,64,2315,Together,Master
2204,3205,52869,1,1,40,84,3,61,2,1,...,0,0,0,0,0,0,66,2781,Married,PHD